version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Password12345!
      DB_NAME: accounts
      JWT_SECRET_KEY: jwt_geheimnisvoll
      FLASK_SECRET_KEY: geheimnisvollesgeheimnis
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../src/users.json:/app/users.json

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Password12345!
      MYSQL_DATABASE: accounts
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../docker/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
